#https://dev.to/stack-labs/my-journey-with-spark-on-kubernetes-in-python-1-3-4nl3
#https://github.com/apache/spark/blob/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile

FROM registry.derp.work/datamechanics-spark3.2.1-java11:0.0.7

USER root

RUN python3 -m pip install --upgrade pip
COPY requirements.txt .

RUN python3 -m pip install -r requirements.txt


## set up sparkmonitor https://pypi.org/project/sparkmonitor/
## reference here; https://towardsdatascience.com/jupyter-notebook-spark-on-kubernetes-880af7e06351



RUN echo "c.InteractiveShellApp.extensions.append('sparkmonitor.kernelextension')" >>  $(ipython profile locate default)/ipython_kernel_config.py

RUN jupyter nbextension install sparkmonitor --py --symlink
RUN jupyter nbextension enable  sparkmonitor --py

RUN ln -s /opt/conda/lib/python3.8/site-packages/sparkmonitor/listener_2.12.jar /opt/spark/jars/listener_2.12.jar

#/home/sparkuser/.local/bin/ipython

## switch back to whatever user the image was on
USER 185


#VOLUME /home/notebook/

CMD jupyter notebook --port=8888 --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token='' --notebook-dir=/home/sparkuser/