apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook-storage
  labels:
    release: jupyter
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs: 
    path: ##replace with your own config
    server: ##replace with your own config